# Generated by Django 4.2.1 on 2023-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='productImage')),
                ('price', models.CharField(max_length=255)),
                ('raring', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
